# Generated by Django 4.1 on 2023-04-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=100)),
                ('certificacion', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10)),
                ('numerocelu', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('genero', models.CharField(max_length=1)),
                ('flexiones', models.IntegerField()),
                ('abdominales', models.IntegerField()),
                ('prueba_aerobica', models.CharField(max_length=5)),
                ('imc', models.FloatField()),
                ('estado', models.CharField(max_length=100)),
                ('metabolismo_basal', models.FloatField()),
                ('calificacion_total', models.FloatField()),
            ],
        ),
    ]
